name: 'Arch Linux User Repository (AUR) GitHub Action'
description: ''
author: 'JamieMagee'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  action:
    description: "Which action to take. Can be 'validate' or 'updpkgsums'"
    required: true
  pkgname:
    description: 'Name of package'
    required: true
  ccache_dir:
    description: "Host path to ccache"
    required: false
    default: ""
runs:
  using: docker
  image: docker://ghcr.io/fabsegp/aur-packages/aur-action@sha256:3f910b4ff73af64cb23159172df591a76336fdbd041683a90bfcec373bc2cfac
  args:
    - ${{ inputs.action }}
    - ${{ inputs.pkgname }}
    - ${{ inputs.ccache_dir }}
