name: 'Arch Linux User Repository (AUR) GitHub Action'
description: ''
author: 'JamieMagee'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  action:
    description: "Which action to take. Can be 'validate' or 'updpkgsums'"
    required: true
  pkgname:
    description: 'Name of package'
    required: true
  ccache_dir:
    description: "Host path to ccache"
    required: false
    default: ""
runs:
  using: docker
  image: docker://ghcr.io/fabsegp/aur-packages/aur-action@sha256:e62c76dabea30d09c79c3c74d5f279df7eef602fe2e65f8c10ac6a0276e0cce2
  args:
    - ${{ inputs.action }}
    - ${{ inputs.pkgname }}
    - ${{ inputs.ccache_dir }}
