name: publish

on:
  push:
    branches: [ main ]
    paths: [ '*/PKGBUILD' ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "pkgbuild=$(git diff --name-only HEAD HEAD~1 "*/PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV

      - name: Update checksums
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          action: 'updpkgsums'
          pkgname: ${{ env.pkgbuild }}

      - name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          file_pattern: '*/PKGBUILD */.SRCINFO'
          commit_message: 'chore: update PKGBUILD checksums'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}

      - name: Pull latest changes
        if: ${{ env.pkgbuild != '' }}
        run: git pull origin main --rebase

      - name: Publish package
        uses: KSXGitHub/github-actions-deploy-aur@abe8ac26b51011c88be58c8809fd2ac674068ea5
        if: ${{ env.pkgbuild != '' }}
        with:
          pkgname: ${{ env.pkgbuild }}
          pkgbuild: ${{ env.pkgbuild }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "ci: update package"
          ssh_keyscan_types: rsa,ecdsa,ed25519
