name: validate and publish package
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      pkgbuild:
        required: true
        type: string
env:
  CCACHE_DIR: .ccache
jobs:
  validate:
    runs-on: ubuntu-latest
    container: ghcr.io/fabsegp/aur-packages/aur-action:main
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Prepare ccache directory
        run: sudo mkdir -p "${{ github.workspace }}/${{ env.CCACHE_DIR }}"
      - name: Cache builds
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ github.workspace }}/${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-cache-${{ inputs.pkgbuild }}-${{ hashFiles(inputs.pkgbuild) }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ inputs.pkgbuild }}-
      - name: Validate package
        run: |
          /entrypoint.sh validate "${{ inputs.pkgbuild }}" "${{ env.CCACHE_DIR }}"
      - name: Update checksums
        run: |
          /entrypoint.sh updpkgsums "${{ inputs.pkgbuild }}"
      - name: Extract version from .SRCINFO
        id: version
        run: |
          srcinfo="${{ inputs.pkgbuild }}/.SRCINFO"
          pkgver=$(grep -m1 'pkgver =' "$srcinfo" | cut -d' ' -f3)
          pkgrel=$(grep -m1 'pkgrel =' "$srcinfo" | cut -d' ' -f3)
          echo "version=${pkgver}-${pkgrel}" >> $GITHUB_OUTPUT
      - name: Publish package
        uses: KSXGitHub/github-actions-deploy-aur@da03e160361ce01bf087e790b6ffd196d7dccff7 # v4.1.3
        with:
          pkgname: ${{ inputs.pkgbuild }}
          pkgbuild: ${{ inputs.pkgbuild }}/PKGBUILD
          assets: ${{ inputs.pkgbuild }}/*
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "ci(${{ inputs.pkgbuild }}): update package to ${{ steps.version.outputs.version }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
