name: validate and publish package
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      pkgbuild:
        required: true
        type: string
env:
  CCACHE_DIR: .ccache
jobs:
  validate:
    runs-on: ubuntu-latest
    container: ghcr.io/fabsegp/aur-packages/aur-action:main
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Prepare ccache directory
        run: sudo mkdir -p "${{ github.workspace }}/${{ env.CCACHE_DIR }}"
      - name: Cache builds
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ github.workspace }}/${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-cache-${{ inputs.pkgbuild }}-${{ hashFiles(inputs.pkgbuild) }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ inputs.pkgbuild }}-
      - name: Validate package
        run: |
          /entrypoint.sh validate "${{ inputs.pkgbuild }}" "${{ env.CCACHE_DIR }}"
      - name: Extract version from .SRCINFO
        id: version
        run: |
          srcinfo="${{ inputs.pkgbuild }}/.SRCINFO"
          pkgver=$(grep -m1 'pkgver =' "$srcinfo" | cut -d' ' -f3)
          pkgrel=$(grep -m1 'pkgrel =' "$srcinfo" | cut -d' ' -f3)
          echo "version=${pkgver}-${pkgrel}" >> $GITHUB_OUTPUT
      - name: Publish package
        uses: KSXGitHub/github-actions-deploy-aur@084b0d9b15415bf9cdb65d44dad1efe37a354050 # v4.2.0
        with:
          pkgname: ${{ inputs.pkgbuild }}
          pkgbuild: ${{ inputs.pkgbuild }}/PKGBUILD
          assets: ${{ inputs.pkgbuild }}/*
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "ci(${{ inputs.pkgbuild }}): update package to ${{ steps.version.outputs.version }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
